"""Create the schema and install the append-only triggers.

Deliberately not Alembic. There is one deployment and no schema history to
migrate, and a half-used migration tool is worse than none — it implies a
guarantee about upgrade paths that has never been exercised. `create_all` is
honest about what this is. The models are ordinary SQLAlchemy, so the day there
is a second deployment to keep in step, `alembic init` and an autogenerated
baseline is a twenty-minute job.

The triggers are the part that matters and they are installed either way: an
audit trail you can quietly edit is not an audit trail.
"""

from __future__ import annotations

from sqlalchemy import inspect

from adapters import db


def main() -> None:
    engine = db.engine()
    db.Base.metadata.create_all(engine)

    with engine.begin() as connection:
        db.install_append_only_triggers(connection)

    tables = sorted(inspect(engine).get_table_names())
    dialect = engine.dialect.name
    print(f"  {len(tables)} tables on {dialect}: {', '.join(tables)}")
    if dialect == "postgresql":
        print(f"  append-only triggers on: {', '.join(db.APPEND_ONLY_TABLES)}")
    else:
        print(
            "  append-only triggers skipped: this is not Postgres, so that "
            "guarantee is not in force here"
        )


if __name__ == "__main__":
    main()
